# Setup
title:               디멘의 블로그
title-en:            Dimen's Blog

tagline:             이데아를 여행하는 히치하이커
description:         이데아를 여행하는 히치하이커

tagline-en:             Alice in Logicland
description-en:         Alice in Logicland

paginate:            5
permalink:           pretty

destination: docs

# About/contact
author:
  name:              최정담
  email:             dimenerno@kaist.ac.kr

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

slugify: default
encoding: UTF-8

url: "https://dimenerno.github.io"
baseurl: ""

google_analytics_id: "G-PVGYLWF7GR"

include:
  - search.json