# Setup
title:               디멘의 블로그
tagline:             이데아를 여행하는 히치하이커
description:         이데아를 여행하는 히치하이커
paginate:            5
permalink:           pretty

destination: docs

# About/contact
author:
  name:              최정담
  email:             dimenerno@kaist.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

slugify: default
encoding: UTF-8

url: "https://dimenerno.github.io"
baseurl: ""

google_analytics:
  id: "G-PVGYLWF7GR"