# Setup
title:               디멘의 블로그
title-en:            Dimen's Blog


paginate:            10
permalink:           pretty

destination: docs

# About/contact
author:
  name:              최정담
  email:             dimen@stanforde.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

slugify: default
encoding: UTF-8

url: "https://dimenerno.github.io"
baseurl: ""

google_analytics_id: "G-PVGYLWF7GR"

include:
  - search.json
  - post-list.json

exclude:
  - post-list.json

collections:
  pages:
    output: true
    permalink: /:path/